###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.7"
services:

    memcached:
      image: memcached:alpine
      container_name: marigold-memcached
      networks:
        - marigold-vnet
        
    redis:
      image: redis:alpine
      container_name: marigold-redis
      networks:
        - marigold-vnet

    mysql:
      image: mysql:8.0
      container_name: marigold-mysql
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=rootuser
        - MYSQL_DATABASE=dbname
        - MYSQL_USER=dbuser
        - MYSQL_PASSWORD=dbpassword
      ports:
        - "3306:3306"
      networks:
        - marigold-vnet

    webserver:
      image: nginx:alpine
      container_name: marigold-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./bin/phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
          - ./src/log/nginx:/var/logs/nginx
      ports:
       - "7575:80"
      networks:
        - marigold-vnet

    php-fpm:
      build: bin/phpdocker/php-fpm
      container_name: marigold-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./bin/phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini
      networks:
        - marigold-vnet

    composer:
      image: composer/composer:1.10.21
      container_name: marigold-composer
      command: ["composer","install"]
      working_dir: /application
      environment:
        - COMPOSER_CACHE_DIR=/application/src/cache/composer
      volumes:
        - .:/application
      depends_on:
        - php-fpm
      networks:
        - marigold-vnet

    phpmyadmin:
      image: phpmyadmin/phpmyadmin:latest
      container_name: marigold-phpymadmin
      working_dir: /application
      ports:
        - 7374:80
      environment:
        - PMA_ARBITRARY=1
        - PMA_HOST=mysql
      depends_on:
        - mysql
      networks:
        - marigold-vnet

networks:
  marigold-vnet:
    driver: bridge
