###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.7"
services:

    memcached:
      image: memcached:alpine
      container_name: marigold-memcached
      networks:
        - marigold-backend

    redis:
      image: redis:alpine
      container_name: marigold-redis
      networks:
        - marigold-backend

    mysql:
      image: mysql:8.0
      container_name: marigold-mysql
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=rootuser
        - MYSQL_DATABASE=dbname
        - MYSQL_USER=dbuser
        - MYSQL_PASSWORD=dbpassword
      ports:
        - "3306:3306"
      networks:
        - marigold-backend

    webserver:
      image: nginx:alpine
      container_name: marigold-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./bin/phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
          - ./src/logs/nginx:/var/logs/nginx
      ports:
       - "7575:80"
      networks:
        - marigold-backend

    php-fpm:
      build: bin/phpdocker/php-fpm
      container_name: marigold-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./bin/phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini
      networks:
        - marigold-backend
      

        
    phpmyadmin:
      image: phpmyadmin/phpmyadmin:latest
      container_name: marigold-phpymadmin
      working_dir: /application
      volumes:
        - ./src/data:/var/lib/mysql
      ports:
        - 7374:80
      environment:
        - PMA_ARBITRARY=1
        - PMA_HOST=mysql
      depends_on:
        - mysql
      networks:
        - marigold-backend

    composer:
      image: composer:1.10.13
      container_name: marigold-composer
      environment:
        - COMPOSER_CACHE_DIR=/src/cache/composer
      volumes:
        - .:/application
      networks:
        - marigold-backend

networks:
  marigold-backend:
    driver: bridge