###############################################################################
#                          Generated on phpdocker.io                          #
# for redis, i added ports, comman and volumes
###############################################################################
version: "3.7"

services:
  redis:
    image: redis:alpine
    container_name: ci3-ultimate-redis
    ports:
      - 6379:6379
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data

  mysql:
    image: mysql:8.0
    container_name: ci3-ultimate-mysql
    volumes:
      - .:/app
    environment:
      - MYSQL_ROOT_PASSWORD=roopassword
      - MYSQL_DATABASE=dbname
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=dbpassword
    ports:
      - "7274:3306"

  webserver:
    image: nginx:alpine
    container_name: ci3-ultimate-webserver
    volumes:
      - .:/app
      - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "7272:80"
    depends_on:
      - redis
      - php-fpm

  php-fpm:
    build: phpdocker/php-fpm
    container_name: ci3-ultimate-php-fpm
    volumes:
      - .:/app
      - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini
    depends_on:
      - redis

  composer:
    image: composer:1.9
    command: ["composer", "install"]
    volumes:
      - .:/app

  mariadb:
    image: mariadb:10.5
    restart: always
    #command: "mysqld --init-file /data/app/init.sql"
    volumes:
      - mariadb-data:/var/lib/mysql
      #- ./init.sql:/data/app/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: qwerty

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8000:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mariadb
    depends_on:
      - mariadb

volumes:
  redis-data:
  mariadb-data:
